name: Deploy to Server (Development)

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: SSH Deploy & Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "Removing old app directory if exists..."
            rm -rf Learning-Application-Web

            echo "Cloning latest code..."
            git clone --branch development git@github-frontend:ASUBRIX/Pudhuyougam---LMS-frontend.git Learning-Application-Web

            cd Learning-Application-Web

            echo "Building Docker image (with user-friendly name)..."
            docker build --no-cache -t pudhuyugam-frontend:latest .

            echo "Stopping and removing existing frontend container if any..."
            docker rm -f pudhuyugam-frontend || true

            echo "Running new frontend container..."
            docker run -d --name pudhuyugam-frontend -p 4000:80 pudhuyugam-frontend:latest

            echo "✅ Deployment complete. Container: pudhuyugam-frontend, Image: pudhuyugam-frontend:latest"
          EOF
