name: Deploy Frontend

on:
  push:
    branches: [development, dev_release]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t lms-frontend .

      - name: Save image to archive
        run: docker save lms-frontend | gzip > lms-frontend.tar.gz

      - name: Copy archive to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "lms-frontend.tar.gz"
          target: "~/frontend"
      
      - name: Run Docker on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p ~/frontend
            cd ~/frontend
            docker load < lms-frontend.tar.gz
            docker stop lms-frontend || true
            docker rm lms-frontend || true
            docker run -d -p 4002:80 --name lms-frontend lms-frontend
      