name: Deploy to Server (Development)

on:
  push:
    branches:
      - dev-release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH Connection
        run: |
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo '✅ SSH SUCCESS from GitHub Actions'"

      - name: Deploy via SSH
        run: |
          ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd Learning-Application-Web-Dev
            git fetch origin dev-release
            git checkout dev-release
            git pull origin dev-release
            docker build -t pudhuyugam-dev:latest .
            docker rm -f pudhuyugam-dev-app || true
            docker run -d --name pudhuyugam-dev-app -p 4000:80 pudhuyugam-dev:latest
            echo "✅ Deployment complete"
          EOF
